export const products = [
  {
    productId: 1,
    productName: "Skincare Skinnex 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product1.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 2,
    productName: "Haircare Flourish 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product2.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 3,
    productName: "Bonecare CalReviv 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product3.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 4,
    productName: "Kidneycare Rena",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product4.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 5,
    productName: "Skincare Skinnex 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product5.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 6,
    productName: "Haircare Flourish 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product6.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 7,
    productName: "Haircare Flourish 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product6.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 8,
    productName: "Haircare Flourish 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product6.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "5",
    isAlmostSoldOut: true,
  },
  {
    productId: 9,
    productName: "Haircare Flourish 1",
    productPrice: "$95.50",
    productImageSrc: "/Images/ProductCardAssets/Product6.svg",
    brandName: "Al Karam",
    reviewCount: "(4.1k)",
    ratingStars: "3",
    isAlmostSoldOut: true,
  },
];
